title: Monitor de Partículas
description: Manual de usuario
theme: jekyll-theme-leap-day
author_name: Miguel Angel Robles R
twitter_username: miguelrsrn
github_username:  ma-robles
instagram_username: mi4rob
email: miguel.robles@atmosfera.unam.mx
url: "https://ma-robles.github.io"
baseurl: "/manual_monitor_pm"
lang: "es-mx"
show_downloads: false
dowloads:
  pdf_url: http://example.com/download.pdf
sections:
  - inicio:
    name: "Inicio"
    url: "index"

  - partes:
    name: "Partes"
    url: "partes"

  - config:
    name: "Configuración"
    url: "config"

  - Instala:
    name: "Instalación"
    url: "instala"

  - ensambla:
    name: "Ensamblado"
    url: "ensambla"

